name: Copilot Setup Steps

on:
  workflow_dispatch:

jobs:
  copilot-setup-steps:
    runs-on: ubuntu-latest
    steps:
      - name: Install Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest

      - name: Install Node # Because strangely ESLint cares about this version
        uses: actions/setup-node@v4
        with:
          node-version: 22.18.0

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install dependencies
        run: bun install

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
